server:
    servlet:
        context-path: /
    port: 8080
spring:
    application:
        name: datatochain
    profiles:
        active: local
    # 强制指定响应头content-type是utf-8编码
    http:
        encoding:
            force: true

swagger:
    base-package: io.nuls.data

logging:
    level:
        io.nuls.data.dao: debug
mybatis:
configuration:
log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


