server:
  servlet:
    context-path: /
  port: 7000
spring:
  application:
    name: spring-boot-admin
  security:
    user:
      name: admin
      password: 123456
      roles: ADMIN
  boot:
    admin:
      notify:
        mail:
          enabled: false  #关闭admin自带的邮件通知
      monitor:
        read-timeout: 200000
      ui:
        title: 服务监控
  mail:
    host: smtp.example.com
    username: admin@example.com #邮箱地址
    password:  xxxxxxxxxx    #授权码
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true

  freemarker:
    settings:
      classic_compatible: true   #解决模板空指针问题




